### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by KatherineJames** [jldowns/vatic-docker-contrib#2]
Hi there -running Windows 10 Enteprise and using powershell in admin mode.
Have used vatic many times over the last few weeks, came back yesterday and suddenly started having this issue, as will be introduced below.

The following commands execute fine (CWD is the folder holding\data)
 docker run -it -p 8080:80 -v C:\.....\data\:/home/vagrant/vagrant_data jldowns/vatic-docker-contrib:latest
/home/vagrant/start_services.sh
cd /home/vagrant/vatic

But now when I try to extract the frames it is not finding the video.
turkic extract /home/vagrant/vagrant_data/DJI_0011.mov /home/vagrant/vagrant_data/frames

Error message:
/home/vagrant/vagrant_data/DJI_0011.mov: No such file or directory
Aborted. Cleaning up...
Traceback (most recent call last):
  File "/usr/local/bin/turkic", line 5, in <module>
    pkg_resources.run_script('turkic==0.2.5', 'turkic')
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 528, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1394, in run_script
    execfile(script_filename, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/turkic-0.2.5-py2.7.egg/EGG-INFO/scripts/turkic", line 16, in <module>
    turkic.cli.main()
  File "/usr/local/lib/python2.7/dist-packages/turkic-0.2.5-py2.7.egg/turkic/cli.py", line 147, in main
    handler(args[1:])
  File "/usr/local/lib/python2.7/dist-packages/turkic-0.2.5-py2.7.egg/turkic/cli.py", line 47, in __init__
    self(parser.parse_args(args))
  File "/home/vagrant/vatic/cli.py", line 48, in __call__
    for frame, image in enumerate(sequence):
  File "/usr/local/lib/python2.7/dist-packages/pyvision-0.3.1-py2.7-linux-x86_64.egg/vision/ffmpeg.py", line 67, in __iter__
    yield self[i]
  File "/usr/local/lib/python2.7/dist-packages/pyvision-0.3.1-py2.7-linux-x86_64.egg/vision/ffmpeg.py", line 53, in __getitem__
    return Image.open(self.getframepath(k))
  File "build/bdist.linux-x86_64/egg/PIL/Image.py", line 2410, in open
IOError: [Errno 2] No such file or directory: '/tmp/pyvision-ffmpeg-24654915/1.jpg'

Any help appreciated urgently.

**Comment by KatherineJames** [comment]
I found a work around. The video in the folder was not mounting with the volume -v command (no idea why), but it is possible to do a manual copy of the video to the container and then attach the docker container again.

docker cp path\to\video\video.mov containerid:/home/vagrant/vagrant_data/video.mov
